### ISSUE TITLE
Is Regularizer option working ?

### ISSUE THREAD

**Issue by arminvburren** [Denys88/rl_games#245]
Hello,

I've been working on OmniIsaacGym from NVIDIA which uses rl_games. In the config files there's an option called "regularizer" in the mlp section: 

```
    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None #'l2_regularizer' # None
        #scale: 10
```

Is this option actually doing something ? I tried activated it and I don't have any visible difference, including with strong scales. 
Where in the code is this used ?

In general is the library still worked on ? There's no commit since 3 month apparently
